apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-python-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-python-app
    app.kubernetes.io/part-of: simple-python-app
  name: simple-python-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: simple-python-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: simple-python-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/simple-python-app/simple-python-app@sha256:5c29fa4eb3d181ca7844df1d33f7286c7f136b10bbd73bef300ab643e98efef7
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
