apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-python-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-python-app
    app.kubernetes.io/part-of: simple-python-app
  name: simple-python-app
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: simple-python-app
status:
  loadBalancer: {}
