apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-python-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-python-app
    app.kubernetes.io/part-of: simple-python-app
  name: simple-python-appqoqt
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: simple-python-app
    weight: null
status: {}
